### ISSUE TITLE
Good env setup

### ISSUE THREAD

**Issue by CodeFromAnywhere** [Code-From-Anywhere/react-with-native#36]
We need to be able to load variables reliably in any react frontend environment that uses webpack as a bundler (React, Next.js, Chrome extensions)

Currently, we get env variables in react native expo using the extra prop in `app.json` (but this doesn't matter as it's bundled using metro bundler).

Maybe it's as simple as adding https://github.com/mrsteele/dotenv-webpack in the next.js project webpack config. Then we can skip using next/config in react components in next.js. 

For the chrome extension we can already access .env in the extension itself. However, it should also replace .env variables (proces.env.XXXX) in the node module that we specify. This should be tested

If we can't get dotenv-webpack to work in next.js, then maybe try to lazy load next/config and only import it if it exists. 

Related:
https://github.com/mrsteele/dotenv-webpack/issues/455

**Comment by Karsens** [comment]
Solution: just use env.JSON
